//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_WEBv1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class envios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public envios()
        {
            this.trazabilidad = new HashSet<trazabilidad>();
        }
        [DisplayName("Numero Guia")]
        public int id_envio { get; set; }
        public int id_sede { get; set; }
        public int id_emisor { get; set; }
        public int id_ciudad_origen { get; set; }
        public int id_receptor { get; set; }
        public int id_ciudad_destino { get; set; }
        public string descripcion_paquete { get; set; }
        public decimal peso { get; set; }
        public decimal valor_declarado { get; set; }
        public decimal largo { get; set; }
        public decimal alto { get; set; }
        public decimal ancho { get; set; }
        public string tipo_envio { get; set; }
        public decimal valor_envio { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string estado_envio { get; set; }
    
        public virtual ciudades ciudades { get; set; }
        public virtual ciudades ciudades1 { get; set; }
        public virtual clientes clientes { get; set; }
        public virtual clientes clientes1 { get; set; }
        public virtual sedes sedes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trazabilidad> trazabilidad { get; set; }
    }
}
