//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_WEBv1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_web_v1LEOEntities : DbContext
    {
        public DB_web_v1LEOEntities()
            : base("name=DB_web_v1LEOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ciudades> ciudades { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<envios> envios { get; set; }
        public virtual DbSet<sedes> sedes { get; set; }
        public virtual DbSet<trazabilidad> trazabilidad { get; set; }
    }
}
